### PR TITLE
Prajwal is in the arena

### PR DESCRIPTION
**Pull request by prajwalp**

### CODE REVIEW

**Comment by giorgionicoletti** [comment]
I want more than a free spritz if I win

**Comment by prajwalp** [comment]
You have the eternal glory of having defeated me

**Comment by giorgionicoletti** [comment]
My pull request wins over yours, I have more stuff

**Comment by prajwalp** [comment]
You will be ostracized for using nuclear arsenal

**Comment by giorgionicoletti** [comment]
Not if I use them fast

**Pull request merged**
